# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\pydantic\_internal\_validate_call.py
# hypothesis_version: 6.137.1

['__annotations__', '__dict__', '__name__', '__qualname__', 'validate_call']