# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\urllib3\connectionpool.py
# hypothesis_version: 6.137.1

[303, '/', '443', '80', 'Connection aborted.', 'GET', 'No host specified.', 'Pool is closed.', 'Redirecting %s -> %s', 'Retry-After', 'Retry: %s', '[', ']', 'errno', 'http', 'https', 'proxy', 'proxy_config', 'socket_options']