# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\aiohttp\web_exceptions.py
# hypothesis_version: 6.137.1

[200, 201, 202, 203, 204, 205, 206, 300, 301, 302, 303, 304, 305, 307, 308, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 421, 422, 424, 426, 428, 429, 431, 451, 500, 501, 502, 503, 504, 505, 506, 507, 510, 511, ',', 'Allow', 'HTTPAccepted', 'HTTPBadGateway', 'HTTPBadRequest', 'HTTPClientError', 'HTTPConflict', 'HTTPCreated', 'HTTPError', 'HTTPException', 'HTTPFailedDependency', 'HTTPForbidden', 'HTTPFound', 'HTTPGatewayTimeout', 'HTTPGone', 'HTTPLengthRequired', 'HTTPMethodNotAllowed', 'HTTPMove', 'HTTPMovedPermanently', 'HTTPMultipleChoices', 'HTTPNoContent', 'HTTPNotAcceptable', 'HTTPNotExtended', 'HTTPNotFound', 'HTTPNotImplemented', 'HTTPNotModified', 'HTTPOk', 'HTTPPartialContent', 'HTTPPaymentRequired', 'HTTPRedirection', 'HTTPRequestTimeout', 'HTTPResetContent', 'HTTPSeeOther', 'HTTPServerError', 'HTTPSuccessful', 'HTTPTooManyRequests', 'HTTPUnauthorized', 'HTTPUpgradeRequired', 'HTTPUseProxy', 'Link', 'Location', 'text']