# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\aiohttp\client.py
# hypothesis_version: 6.137.1

[101, 301, 302, 303, 307, 308, 1024, 8190, ',', '/', '13', 'BaseConnector', 'CIMultiDict[str]', 'ClientConnectorError', 'ClientError', 'ClientHttpProxyError', 'ClientOSError', 'ClientPayloadError', 'ClientRequest', 'ClientResponse', 'ClientResponseError', 'ClientSSLError', 'ClientSession', 'ClientTimeout', 'ClientWSTimeout', 'ContentTypeError', 'DELETE', 'Fingerprint', 'GET', 'HEAD', 'InvalidURL', 'NamedPipeConnector', 'OPTIONS', 'PUT', 'RedirectClientError', 'RequestInfo', 'ServerTimeoutError', 'Session is closed', 'SocketTimeoutError', 'TCPConnector', 'TRACE', 'TooManyRedirects', 'UnixConnector', 'Upgrade', 'WSMessageTypeError', '_RetType', '_auto_decompress', '_base_url', '_base_url_origin', '_connector', '_connector_owner', '_cookie_jar', '_coro', '_default_auth', '_default_headers', '_default_proxy', '_default_proxy_auth', '_json_serialize', '_loop', '_max_field_size', '_max_line_size', '_raise_for_status', '_read_bufsize', '_request_class', '_resolve_charset', '_resp', '_response_class', '_retry_connection', '_session', '_skip_auto_headers', '_source_traceback', '_timeout', '_trace_configs', '_trust_env', '_version', '_ws_response_class', 'asyncio.Future[Any]', 'client_session', 'message', 'request', 'requote_redirect_url', 'source', 'source_traceback', 'upgrade', 'utf-8', 'websocket']